FROM registry.access.redhat.com/ubi9/python-39:latest
WORKDIR /summarizer
COPY builds/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /summarizer/requirements.txt
COPY summarizer.py .
EXPOSE 8501
ENTRYPOINT [ "streamlit", "run", "summarizer.py" ]