# Install the app dependencies in a full UBI Node docker image
FROM registry.access.redhat.com/ubi9/nodejs-20:9.5-1743584090

# Copy package.json
COPY --chown=default:root --chmod=0775 package*.json ./
COPY --chown=default:root --chmod=0775 ./ ./

# Install npm packages
RUN npm install

ENV NODE_ENV production

USER 1001
EXPOSE 8501

ENV PORT 8501

CMD ["sh", "-c", "HOSTNAME=0.0.0.0 node ."]

