FROM registry.access.redhat.com/ubi9/python-39:1-158
WORKDIR /locallm
COPY requirements.txt /locallm/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /locallm/requirements.txt
COPY upload_file_ui.py /locallm/
ENTRYPOINT [ "python", "upload_file_ui.py"]