FROM registry.access.redhat.com/ubi9/python-311:1-72.1722518949
WORKDIR /function-call
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /function-call/requirements.txt
COPY *.py .
EXPOSE 8501
ENTRYPOINT [ "streamlit", "run", "app.py" ]
