FROM registry.access.redhat.com/ubi9/python-311:1-72.1722518949
USER root
ENV LD_LIBRARY_PATH="/usr/local/lib"
####
WORKDIR /rag
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /rag/requirements.txt
COPY rag_app.py .
COPY manage_graphdb.py .
EXPOSE  8501
ENV  HF_HUB_CACHE=/rag/models/
RUN mkdir -p /rag/models/
RUN chgrp -R 0 /rag/models/ && chmod -R g=u /rag/models/
ENTRYPOINT [ "streamlit", "run" ,"rag_app.py" ]
