---
- name: Test Environment Provisioning
  hosts: test_environments
  remote_user: fedora
  become: true
  gather_facts: false

  tasks:
  
  - name: Wait until the instance is ready
    ansible.builtin.wait_for_connection:
    delay: 15
    timeout: 180
  
  - name: Gather facts for first time
    ansible.builtin.setup:

  - name: Check Podman Present
    ansible.builtin.package:
      name: podman
      state: present

  - name: Bootc install
    ignore_unreachable: true
    containers.podman.podman_container:
      name: "{{ image_name }}"
      image: "quay.io/ai-lab/{{ image_name }}:latest"
      state: started
      auto_remove: yes
      cap_add:
        - sys_admin
      security_opt:
        - "label=type:unconfined_t"
      volumes:
        - "/:/target"
        - "/var/lib/containers:/var/lib/containers"
      privileged: yes
      pid_mode: host
      command: "bootc install to-filesystem --karg=console=ttyS0,115200n8 --replace=alongside /target"

  - name: Restart instance
    ansible.builtin.reboot:

  - name: Check if ssh was successful
    ansible.builtin.shell: pwd
