FROM registry.access.redhat.com/ubi9/python-39:1-158
### Update sqlite for chroma
USER root
RUN dnf remove sqlite3 -y
RUN  wget https://www.sqlite.org/2023/sqlite-autoconf-3410200.tar.gz
RUN tar -xvzf sqlite-autoconf-3410200.tar.gz
WORKDIR sqlite-autoconf-3410200
RUN ./configure
RUN make
RUN make install
RUN mv /usr/local/bin/sqlite3 /usr/bin/sqlite3
ENV LD_LIBRARY_PATH="/usr/local/lib"
### Permssions for chroma
WORKDIR /locallm
RUN mkdir /data
###
COPY src .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /locallm/requirements.txt
ENTRYPOINT [ "python", "rag_service.py" ]
