FROM registry.access.redhat.com/ubi9/python-311:1-52
ARG PORT=8501
WORKDIR /locallm
COPY requirements.txt /locallm/requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --upgrade -r requirements.txt
COPY object_detection_client.py object_detection_client.py
EXPOSE $PORT
ENTRYPOINT [ "streamlit", "run", "object_detection_client.py" ]
