FROM registry.access.redhat.com/ubi9/python-39:latest
WORKDIR /rag
COPY rag/ai_applications/base/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /rag/requirements.txt
ENV MODEL_ENDPOINT=http://10.88.0.1:7860
EXPOSE 8080
COPY rag/ai_applications/rag_chat.py .
ENTRYPOINT [ "python", "rag_chat.py" ]