FROM quay.io/centos-bootc/centos-bootc:stream9

ARG MODEL_REPO=https://huggingface.co/ibm/granite-7b-base
ARG MODEL_PATH=/usr/share/ai-model

RUN dnf install -y git-lfs
RUN mkdir -p "${MODEL_PATH}"
RUN git clone --progress --verbose "${MODEL_REPO}" "${MODEL_PATH}"
