FROM registry.access.redhat.com/ubi9/python-39:1-158
WORKDIR /locallm
COPY builds/requirements.txt /locallm/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /locallm/requirements.txt
ENV MODEL_FILE=llama-2-7b-chat.Q5_K_S.gguf
COPY builds/${MODEL_FILE} /locallm/models/
COPY builds/src/ /locallm
COPY chat_service.py /locallm/chat_service.py
EXPOSE 7860
ENTRYPOINT [ "python", "chat_service.py" ]
