FROM registry.access.redhat.com/ubi9/python-311:1-72.1722518949
USER 0
RUN dnf install -y python3-dnf-plugin-versionlock && \
    dnf install -y \
https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf copr enable -y slp/mesa-krunkit epel-9-aarch64 && \
    dnf install -y mesa-vulkan-drivers-23.3.3-101.el9.aarch64 && \
    dnf versionlock mesa-vulkan-drivers-23.3.3-101.el9.aarch64 && \
    dnf install -y git cmake ninja-build gcc gcc-c++ vulkan-loader-devel vulkan-tools
USER 1001
WORKDIR /locallm
COPY src .
RUN pip install --upgrade pip
ENV CMAKE_ARGS="-DLLAMA_VULKAN=on"
ENV FORCE_CMAKE=1
RUN pip install --no-cache-dir --upgrade -r /locallm/requirements.txt
ENTRYPOINT [ "sh", "run.sh" ]
