FROM registry.access.redhat.com/ubi9/python-311:1-77.1726664316
WORKDIR /agents
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /agents/requirements.txt
COPY *.py .
EXPOSE 8501
ENTRYPOINT [ "streamlit", "run", "react-agent-app.py" ]
