# This containerfile downloads a model and embeds a text generation application
FROM registry.access.redhat.com/ubi9:9.3-1361.1699548029 AS model
WORKDIR /locallm
ARG MODEL_URL=https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/resolve/main/llama-2-7b-chat.Q4_K_M.gguf?download=true
ARG MODEL_FILE=llama-2-7b-chat.Q4_K_M.gguf
RUN dnf install -y wget
RUN wget -O $MODEL_FILE $MODEL_URL

FROM registry.access.redhat.com/ubi9/python-311:1-34.1699551735
WORKDIR /locallm
ARG MODEL_FILE=llama-2-7b-chat.Q4_K_M.gguf
COPY ../requirements.txt /locallm/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /locallm/requirements.txt
ENV MODEL_FILE=$MODEL_FILE
COPY --from=model /locallm/${MODEL_FILE} /locallm/
COPY ../src/ /locallm
ENTRYPOINT [ "python", "app.py" ]

