FROM registry.access.redhat.com/ubi9/python-312:1-10.1716478623
WORKDIR /summarizer
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /summarizer/requirements.txt
COPY summarizer.py .
EXPOSE 8501
ENTRYPOINT [ "streamlit", "run", "summarizer.py" ]
