FROM registry.access.redhat.com/ubi9/python-311:1-52
ARG PORT=8501
WORKDIR /summarizer
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /summarizer/requirements.txt
COPY summarizer.py .
EXPOSE $PORT
ENTRYPOINT [ "streamlit", "run", "summarizer.py" ]
