FROM registry.access.redhat.com/ubi9/python-311:1-52
ARG PORT
WORKDIR /chat
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /chat/requirements.txt
COPY chatbot_ui.py .
EXPOSE $PORT
ENTRYPOINT [ "streamlit", "run", "chatbot_ui.py" ]
