#!/bin/bash

# Template values replaced by container build
ENDPOINT_URL="__REPLACE_ENDPOINT_URL__"
TRAIN_DEVICE="__REPLACE_TRAIN_DEVICE__"
CONTAINER_DEVICE="__REPLACE_CONTAINER_DEVICE__"
IMAGE_NAME="__REPLACE_IMAGE_NAME__"
GPU_AMOUNT="__REPLACE_GPU_AMOUNT__"
NPROC_PER_NODE="__REPLACE_NPROC_PER_NODE__"
EFFECTIVE_BATCH_SIZE="__REPLACE_EFFECTIVE_BATCH_SIZE__"

# HF caching uses relative symlink structures, so keep cache relative to
# the central working directory
CONTAINER_CACHE="/instructlab/cache"
HOST_CACHE="$(pwd)/cache"
WORKDIR="$(pwd)/model"

has_argument() {
	match=$1
	shift
	for arg in "$@"; do
		if [[ "$arg" == *"$match"* ]]; then
			return 0
		fi
	done
	return 1
}

mkdir -p "${HOST_CACHE}"
PODMAN_COMMAND=("podman" "run" "--rm" "-it" "--device" "${CONTAINER_DEVICE}" \
		"--security-opt" "label=disable" "--net" "host" \
		"-v" "${WORKDIR}:/instructlab" "--entrypoint" "" \
		"-e" "HF_HOME=${CONTAINER_CACHE}" \
		"${CONTAINER_NAME}")
PODMAN_COMMAND_SERVE=("podman" "run" "--rm" "-it" "--device" "${CONTAINER_DEVICE}" \
		"--security-opt" "label=disable" "--net" "host" \
		"-v" "${WORKDIR}:/instructlab" \
		"-e" "HF_HOME=${CONTAINER_CACHE}" \
		"${CONTAINER_NAME}" "--chat-template=mixtral.jinja" "--host=0.0.0.0" "--port=8080" "--model=/instructlab" "--tensor-parallel-size=${GPU_AMOUNT}")
if [[ "$1" = "init" ]]; then
	if ! has_argument "--repository" "$@"; then
		shift
		"${PODMAN_COMMAND[@]}" ilab init \
			--repository https://github.com/instructlab/taxonomy.git "$@"
		exit $?
	fi
elif [[ "$1" = "train" ]]; then
	if ! has_argument "--nproc_per_node" "$@" || ! has_argument "--effective_batch_size" "$@"; then
		shift
		../deepspeed/launch_training.sh ${NPROC_PER_NODE} ${EFFECTIVE_BATCH_SIZE} ${TRAIN_DEVICE}
		exit $?
	fi
elif [[ "$1" = "serve" ]]; then
	# run vllm container which will serve vllm and ilab generate
	"${PODMAN_COMMAND_SERVE[@]}"
	exit $?
elif [[ "$1" = "generate" ]]; then
	# run vllm container which will serve vllm and ilab generate.
	if ! has_argument "--endpoint-url" "$@"; then
		shift
		"${PODMAN_COMMAND[@]}" ilab generate --model /mnt/model/ --model-family=mixtral --num-instructions 5000 --endopoint-url ${ENDPOINT_URL} "$@"
		exit $?
	fi
fi

"${PODMAN_COMMAND[@]}" ilab "$@"

