FROM registry.access.redhat.com/ubi9/python-312:1-10.1716478623
WORKDIR /image_understanding
COPY requirements.txt .
RUN pip install --upgrade pip && \
  pip install --no-cache-dir --upgrade -r requirements.txt
COPY image_understanding.py .
EXPOSE 8501
ENTRYPOINT [ "streamlit", "run", "image_understanding.py" ]
