FROM registry.access.redhat.com/ubi9/python-311:1-52
ARG PORT=8501
WORKDIR /image_understanding
COPY requirements.txt .
RUN pip install --upgrade pip && \
  pip install --no-cache-dir --upgrade -r requirements.txt
COPY image_understanding.py .
EXPOSE $PORT
ENTRYPOINT [ "streamlit", "run", "image_understanding.py" ]
