FROM registry.access.redhat.com/ubi9/python-39:1-158
WORKDIR /locallm
RUN git clone https://github.com/michaelclifford/llama.cpp.git
RUN cd llama.cpp/ && make
ENV DATA=data/data/shakespeare.txt
ENV MODEL_FILE=data/llama-2-7b-chat.Q5_K_S.gguf
ENV NEW_MODEL=shakespeare-lora.gguf
COPY run_finetune.sh /locallm/
ENTRYPOINT ["sh", "run_finetune.sh"]
