FROM quay.io/containers/podman:v4.9.3

USER root

COPY playground/tests/requirements.txt .

RUN dnf install -y python3.11 python3-pip buildah git && \
    dnf clean all && \
    pip3 install -r requirements.txt 
