FROM quay.io/containers/podman:v4.9.4

USER root

COPY requirements-test.txt .

RUN dnf install -y python3.11 python3-pip buildah git make && \
    dnf clean all && \
    pip3 install -r requirements-test.txt 
