FROM quay.io/centos-bootc/centos-bootc:stream9

ADD rocm.repo /etc/yum.repos.d/rocm.repo

ARG EXTRA_RPM_PACKAGES=''
RUN dnf install -y \
  rocm-smi \
  ${EXTRA_RPM_PACKAGES} \
  && dnf clean all

ARG INSTRUCTLAB_IMAGE="quay.io/ai-lab/instructlab-amd:latest"

# Setup /usr/lib/containers/storage as an additional store for images.
# Remove once the base images have this set by default.
RUN sed -i -e '/additionalimage.*/a "/usr/lib/containers/storage",' \
        /etc/containers/storage.conf && \
	cp /run/.input/ilab /usr/local/bin/ilab

ARG INSTRUCTLAB_IMAGE
ARG INSTRUCTLAB_IMAGE_ID

RUN sed -i 's/__REPLACE_TRAIN_DEVICE__/cuda/' /usr/local/bin/ilab
RUN sed -i 's/__REPLACE_CONTAINER_DEVICE__/nvidia.com\/gpu=all/' /usr/local/bin/ilab
RUN sed -i "s%__REPLACE_CONTAINER_NAME__%${INSTRUCTLAB_IMAGE}%" /usr/local/bin/ilab

# Added for running as an OCI Container to prevent Overlay on Overlay issues.
VOLUME /var/lib/containers

# Prepull the instructlab image
RUN podman --root /usr/lib/containers/storage pull oci:/run/.input/${INSTRUCTLAB_IMAGE_ID}
RUN podman --root /usr/lib/containers/storage image tag ${INSTRUCTLAB_IMAGE_ID} ${INSTRUCTLAB_IMAGE}
