FROM registry.access.redhat.com/ubi9/python-39:1-158
WORKDIR /locallm
COPY src .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /locallm/requirements.txt
ENTRYPOINT [ "python", "summary_service.py" ]
