
FROM quay.io/opendatahub/workbench-images:cuda-ubi9-python-3.9-20231206
WORKDIR /locallm
COPY ../requirements.txt /locallm/requirements.txt
RUN pip install --upgrade pip
ENV CMAKE_ARGS="-DLLAMA_CUBLAS=on"
ENV FORCE_CMAKE=1
RUN pip install --upgrade --force-reinstall --no-cache-dir -r /locallm/requirements.txt
ENV MODEL_FILE=llama-2-7b-chat.Q5_K_S.gguf
COPY ../${MODEL_FILE} /locallm/
COPY ../src/ /locallm
ENTRYPOINT [ "python", "app.py" ]
