name: Update quay.io/ai-lab model images

on:
  pull_request:
    branches:
      - main
    paths:
      - 'convert_models/**'
      - '!convert_models/README.md'
      - '.github/workflows/model-converter.yaml'
  push:
    branches:
      - main
    paths:
      - 'convert_models/**'
      - '!convert_models/README.md'
      - '.github/workflows/model-converter.yaml'
  
  workflow_dispatch:

env:
  REGISTRY: quay.io
  REGISTRY_ORG: ai-lab

jobs:
  build-and-push-model-image:
    if: "!contains(github.event.pull_request.labels.*.name, 'hold-tests')"
    strategy:
      matrix:
        include:
          - platforms: linux/amd64,linux/arm64
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - uses: actions/checkout@v4.1.4

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: ${{ env.REGISTRY_ORG }}/model-converter
          platforms: ${{ matrix.platforms }}
          tags: latest
          containerfiles: convert_models/Containerfile
          context: convert_models

      - name: Login to Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: redhat-actions/podman-login@v1.7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: redhat-actions/push-to-registry@v2.8
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
